---

name: test-phaser-3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: unit-tests

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Run npm install
        run: npm install

      - name: Build js
        run: npm run build:js

      - name: Run tests
        run: npm run test3
        env:
          CI: true
